
package de.htwg_konstanz.ebus.wholesaler.ws.updateCatalog;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "updateCatalog", targetNamespace = "http://www.example.org/updateCatalog/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UpdateCatalog {


    /**
     * 
     * @param requestPart
     * @return
     *     returns de.htwg_konstanz.ebus.wholesaler.ws.updateCatalog.UpdateResponseType
     * @throws AuthentificationMessage
     */
    @WebMethod(action = "http://localhost:8080/updateCatalog/updateCatalog")
    @WebResult(name = "response", targetNamespace = "http://www.example.org/updateCatalog/", partName = "responsePart")
    public UpdateResponseType updateCatalog(
        @WebParam(name = "request", targetNamespace = "http://www.example.org/updateCatalog/", partName = "requestPart")
        UpdateRequestType requestPart)
        throws AuthentificationMessage
    ;

}
